### ISSUE TITLE
Does this mod work with Dmc HD collection?

### ISSUE THREAD

**Issue by Mad4point0** [muhopensores/dmc3-inputs-thing#16]
Cool mod, i hate only being able to use 2 weapons. Feels weird after playing Dmc5 and the guide vid said DMC3 OG port so, just wanted to make sure

**Comment by ProjectXsent** [comment]
Yes this is only for the OG 2006 PC port.

**Comment by muhopensores** [comment]
OG port has styleswitcher with >2 weapon support look for WeaponSwitcher section in StyleSwitcher.ini
