### ISSUE TITLE
If you install this mod, XInput Plus will be disabled and you will not be able to use the trigger buttons.

### ISSUE THREAD

**Issue by frog4510** [muhopensores/dmc3-inputs-thing#3]
I installed it according to the procedure.
The installation itself was successful, but XInput Plus stopped making success sounds and the trigger buttons became unusable.
I apologize for my unnatural English. I am using translation software.

**Comment by muhopensores** [comment]
Should be fixed in 5f2fddf55d54e4f90dec407666c7a49fcf2de0eb either loading dinput8_original.dll or using GamepadFixes mod in ui.
new build in releases https://github.com/muhopensores/dmc3-inputs-thing/releases/tag/1.01a
